### ISSUE TITLE
Use "server" or "storage" instead of  "POD"

### ISSUE THREAD

**Issue by csarven** [solid/solid-prep#10]

**Comment by CxRes** [comment]
I was hoping that by now, CG would officially define PODS. This has been a request I had made previously as well. If that does not happen, at some point though, I will make the change.

**Comment by csarven** [comment]
The CG actually went away from it because it wasn't particularly a technical term for specifications, and that it was used in informal writing for the most part. The other reason was because there are other terms such as server or storage that are more adequate for the context in which they're used.

https://github.com/solid/specification/pull/476
https://github.com/solid/specification/pull/365
https://github.com/solid/specification/pull/475

So, I suggest using a term that's a product class from specifications.
