### ISSUE TITLE
Add a Note about the subject IRI of the Activity

### ISSUE THREAD

**Issue by csarven** [solid/solid-prep#11]
In https://github.com/nodeSolidServer/node-solid-server/issues/1799 , I mentioned that the Activity could use an HTTP URI or a bnode (with UUID values in the string).

I think the spec could use a Note for server implementers to consider what they might want to use where/when...

**Comment by CxRes** [comment]
I am assigning this to you. Please propose a PR!

**Comment by csarven** [comment]
I think this is the relevant part:

>id `<xs:string>`
>    an opaque identifier for the notification. Can be used to set `Last-Event-ID` in a subsequent PREP notifications request. 

1. If `id` is the subject of event/activity (at least for those that are represented in RDF using AS2 etc.), then it it needs to be a URI or a bnode. So, I think saying that it is a string may be an issue here.

2. The `id` could be used as a value for `Last-Event-ID` but the description of the event should express that. So, there needs to be a property along the lines of "previous", e.g., `http://www.w3.org/ns/iana/link-relations/relation`. Not sure if you can find anything specific to "previous/last event" (unless you change the payload a lot more and get into collections/paging territory). I don't see an issue using a URI including a unique path but you can follow up on that. `https://example.org/activity/{uuid}`, `https://example.org/.well-known/genid/{uuid}`, `urn:uuid:{uuid}`, `_:{uuid}` should do.

```json
{
  "id": "urn:uuid:0798c962-1879-448f-af44-f83162a029be",
  "published": "2024-11-07T14:15:58Z",
  "type": "Add",
  "object": "/dokieli/inbox/fa6ec1e0-dd3f-4b1f-b915-6dc3311351af.ttl",
  "target": "https://csarven.localhost/dokieli/inbox/",
  "state": "W/\"7-rM9AyJuqT6iOan/xHh+AW+7K/T8\"",
  "http://www.w3.org/ns/iana/link-relations/relation#prev": { "id": "urn:uuid:ee641336-dfd4-4004-9ed2-c0ef0d11d844" },
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://www.w3.org/ns/solid/notification/v1"
  ]
}
```

**Comment by CxRes** [comment]
See https://github.com/solid/notifications/issues/199

**Comment by csarven** [comment]
Noting here as well: on second thought, I would suggest against using bnodes. These events should have an identity, so stick to IRIs.

**Comment by CxRes** [comment]
I have created PR#17 that fixes the Data Model with neutral language.

If you still feel strongly, we can add an advisory that implantations should use IRIs and not blank nodes.

**Comment by csarven** [comment]
I think that systems that use bnodes in the end may have a hard time dealing with them in auditing cases or recalling the notifications. My sense is that these activities need to be treated as unique and persistent identifiers. bnodes will pose a problem all around. I don't have implementation experience on this at this point obviously.

**Comment by CxRes** [comment]
> I think...

We need to discuss this in the context of SNP!
