### ISSUE TITLE
Consider including POST in table for when contained resources are created

### ISSUE THREAD

**Issue by csarven** [solid/solid-prep#13]
Should table 4 include `POST`?

The Add activity is typical use of adding something to a container (e.g., use case being an inbox) with `POST`. That'd trigger an activity in which the resource (as:object) that's created in the container (as:target).

**Comment by CxRes** [comment]
Good catch! When you create a resource, that is not a container, using `POST`, absolutely. 

But probably not for containers, where it should be Update. Thoughts?

**Comment by csarven** [comment]
Yes? If I'm not misunderstanding the question.

POST /foo/, then /foo/bar will be created (201). In other words, the resource at /foo/bar gets added to the container at /foo/.

**Comment by CxRes** [comment]
I meant `POST /foo/bar` when `/foo/bar` does not exist.  

Table 4 refers to the case where the target of the HTTP operation is itself in a container and non-existent. Could do with better language, perhaps.

**Comment by csarven** [comment]
Can't create (404) or update (403) with POST /foo/bar. Only need to describe the scenario in which:

GET /foo/

POST /foo/
Location /foo/bar

The PREP notification will be an as:Add; as:object /foo/bar; as:target /foo/.
